### ISSUE TITLE
Cannot import name mcts_search

### ISSUE THREAD

**Issue by leelening** [hildensia/mcts#2]
Hey,

I intall the package, but when I run:
- python experiments/toy_world.py 
It says cannot import mcts_search. Did I do something wrong?

**Comment by hildensia** [comment]
hi. i'll have a look into it on Friday or Monday. Sorry -- busy right now :)

**Comment by hildensia** [comment]
Hi, seems like the `experiment` folder is outdated. Have a look at the `test` folder. The tests use the current api. Thanks for the issue, I'll update the experiment folder...

**Comment by zoupei123456** [comment]
what is usage and how to use it?Where the code should be added？please tell me, thanks,
