### ISSUE TITLE
How to use your code？

### ISSUE THREAD

**Issue by zoupei123456** [hildensia/mcts#3]
what is  usage and how to use it?Where the code should be added？please tell me, thanks,

**Comment by hildensia** [comment]
Have you followed the example in the readme?

**Comment by zoupei123456** [comment]
Yes,I read the code in the readme,I do not know where the code should be added

**Comment by hildensia** [comment]
I mean, it's a complete example. you just put it all in a python file and run it, after you installed (`python setup.py install`) the package. Don't forget to import the required things from the MCTS package (e.g.`from mcts import *`, although you8 should aim for solely importing things that you really need)

What do you mean with 'where the code should be added'?

**Comment by zoupei123456** [comment]
mcts = MCTS(tree_policy=UCB1(c=1.41), 
            default_policy=immediate_reward,
            backup=monte_carlo)

root = StateNode(MazeState([0, 0]))
best_action = mcts(root)
these code ,where the code should be added?

**Comment by hildensia** [comment]
in your `main`, or where ever you want it to run. I don't want to seem rude, but I have the feeling you're python skills might need some refreshing. May I suggest https://learnpythonthehardway.org/ ?
