### ISSUE TITLE
something wrong with the demo

### ISSUE THREAD

**Issue by luhengtong** [hildensia/mcts#4]
Hey,
    I want to run the demo in the README. But something was wrong. The message is as follows:

    root = StateNode(state=MazeState([0, 0]))
TypeError: __init__() missing 1 required positional argument: 'parent'

what can I do for the error? 
    Thanks for your help!

**Comment by luhengtong** [comment]
I change the code as follows:

    root = StateNode(parent=None, state=MazeState([0, 0]))

It worked.

**Comment by hildensia** [comment]
Cool. I'll fix it in the readme. Thanks for pointing it out.
